import assert from 'node:assert/strict';
import { listReports } from './reports.service.ts';
const queries = [];
const client = { trReport: { findMany: async query => { queries.push(query); return []; }, count: async query => { queries.push(query); return 0; } }, $transaction: promises => Promise.all(promises) };
const admin = { id: 'test-admin', role: 'ADMIN' };
let result = await listReports(admin, { page: 1, pageSize: 20 }, true, client);
assert.equal(result.meta.total, 0);
assert.deepEqual(result.data, []);
assert.equal(queries[0].where.reporterId, undefined);
assert.equal(queries[0].where.reviewStatus, undefined);
assert.equal(queries[0].where.OR, undefined);
queries.length = 0;
result = await listReports(admin, { page: 2, pageSize: 20, reviewStatus: 'REVIEWED' }, true, client);
assert.equal(result.meta.page, 2);
assert.equal(queries[0].skip, 20);
assert.equal(queries[0].where.reviewStatus, 'REVIEWED');
assert.deepEqual(queries[0].where, queries[1].where);
await assert.rejects(listReports({ id: 'citizen', role: 'USER' }, {}, true, client), /Administrator access/);
queries.length = 0;
await listReports({ id: 'citizen', role: 'USER' }, {}, false, client);
assert.equal(queries[0].where.reporterId, 'citizen');
