import { Router, raw } from 'express';
import { saveAvatar, readAvatar, readAdminAvatar, saveAdminAvatar } from '../profile/index.js';
import { rateLimit } from 'express-rate-limit';
import { sessionGuard, adminGuard } from '../../middleware/index.js';
import { enums, type Actor } from '../../types/index.js';
import { routeId } from '../../utils/index.js';
import { list, single } from './api.controller.js';
import * as reports from '../reports/index.js';
import * as uploads from '../uploads/index.js';
import * as admin from '../admin/index.js';
import * as integrations from '../integrations/index.js';
import * as publicApi from '../public/index.js';
import * as notifications from '../notifications/index.js';
import { nearbyPreferences, saveNearbyLocation } from '../notifications/nearby.service.js';
import { searchPlaces } from '../public/places.js';

const router = Router();
const expensive = rateLimit({ windowMs: 60000, limit: 6, standardHeaders: 'draft-8', legacyHeaders: false, message: { message: 'Too many requests', code: 'RATE_LIMIT' } });
const writes = rateLimit({ windowMs: 60000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false, message: { message: 'Too many requests', code: 'RATE_LIMIT' } });
function auditReason(value: string | undefined) { try { return decodeURIComponent(value ?? ''); } catch { return ''; } }
router.get('/public/site', single(() => admin.getSettings()));
router.get('/public/information', list(req => admin.listInformation(req.query)));
router.get('/public/information/:slug', single(req => admin.getInformation(routeId(req, 'slug'))));
router.get('/public/regions', single(req => publicApi.regions(req.query)));
router.get('/public/enums', single(() => enums));
router.get('/public/media/:id', single(req => uploads.publicDownload(routeId(req))));
router.get('/public/media/:id/content', async (req, res) => { const item = await uploads.publicContent(routeId(req)); res.setHeader('Content-Type', item.contentType); res.setHeader('Content-Length', String(item.bytes.length)); res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('Cache-Control', 'private, max-age=30'); res.send(item.bytes); });
router.use(sessionGuard);
router.get('/places', rateLimit({ windowMs: 60000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false, message: { message: 'Too many place searches. Please wait.', code: 'RATE_LIMIT' } }), single(req => searchPlaces(req.query)));
router.post('/profile/:id/avatar', expensive, raw({ type: 'image/jpeg', limit: '1mb' }), single((req, res) => saveAvatar(res.locals.actor as Actor, routeId(req), req.body)));
router.get('/profile/:id/avatar', async (req, res) => {
  const bytes = await readAvatar(res.locals.actor as Actor, routeId(req));
  res.setHeader('Cache-Control', 'private, no-store');
  res.setHeader('Content-Type', 'image/jpeg');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.send(bytes);
});
router.get('/map', single((req, res) => { res.setHeader('Cache-Control', 'private, no-store'); return publicApi.roleMap(res.locals.actor as Actor, req.query); }));
router.get('/feed', list((req, res) => reports.listCitizenFeed(res.locals.actor as Actor, req.query)));
router.get('/notifications/preferences', single((_req, res) => { res.setHeader('Cache-Control', 'private, no-store'); return nearbyPreferences(res.locals.actor as Actor); }));
router.post('/notifications/location', expensive, single((req, res) => saveNearbyLocation(res.locals.actor as Actor, req.body)));
router.get('/notifications', list((req, res) => notifications.listNotifications(res.locals.actor as Actor, req.query)));
router.patch('/notifications/:id/read', writes, single((req, res) => notifications.markNotificationRead(res.locals.actor as Actor, routeId(req))));
router.post('/notifications/read-all', writes, single((_req, res) => notifications.markAllNotificationsRead(res.locals.actor as Actor)));
router.get('/reports', list((req, res) => reports.listReports(res.locals.actor as Actor, req.query)));
router.post('/reports', writes, single((req, res) => reports.createReport(res.locals.actor as Actor, req.body), 201));
router.get('/reports/:id', single((req, res) => reports.getReport(res.locals.actor as Actor, routeId(req))));
router.post('/reports/:id/updates', writes, single((req, res) => reports.addReportUpdate(res.locals.actor as Actor, routeId(req), req.body), 201));
router.post('/uploads/intents', writes, single((req, res) => uploads.createIntent(res.locals.actor as Actor, req.body), 201));
router.put('/uploads/:id/content', expensive, raw({ type: ['image/jpeg', 'image/png', 'image/webp'], limit: '5mb' }), single((req, res) => uploads.uploadContent(res.locals.actor as Actor, routeId(req), req.body, req.get('Content-Type')?.split(';')[0]?.trim() ?? '')));
router.post('/uploads/:id/finalize', writes, single((req, res) => uploads.finalize(res.locals.actor as Actor, routeId(req))));
router.get('/uploads/:id/download', single((req, res) => uploads.download(res.locals.actor as Actor, routeId(req))));
router.get('/uploads/:id/content', async (req, res) => { const item = await uploads.privateContent(res.locals.actor as Actor, routeId(req)); res.setHeader('Content-Type', item.contentType); res.setHeader('Content-Length', String(item.bytes.length)); res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('Cache-Control', 'private, max-age=30'); res.send(item.bytes); });
router.use('/admin', adminGuard);
router.get('/admin/enums', single(() => enums));
router.get('/admin/layers', single(() => admin.listLayers()));
router.post('/admin/layers', single((req, res) => admin.importLayer(res.locals.actor as Actor, req.body), 201));
router.get('/admin/regions', single(req => admin.listRegions(req.query)));
router.post('/admin/regions', single((req, res) => admin.createRegion(res.locals.actor as Actor, req.body), 201));
router.get('/admin/features', list(req => admin.listFeatures(req.query)));
router.get('/admin/hotspots', list(req => admin.listHotspots(req.query)));
router.get('/admin/cases', list(req => admin.listCases(req.query)));
router.post('/admin/cases', single((req, res) => admin.createCase(res.locals.actor as Actor, req.body), 201));
router.post('/admin/cases/from-reports', writes, single((req, res) => admin.createCaseFromReports(res.locals.actor as Actor, req.body), 201));
router.get('/admin/cases/:id', single((req, res) => { res.setHeader('Cache-Control', 'private, no-store'); return admin.getCase(routeId(req), res.locals.actor as Actor); }));
router.patch('/admin/cases/:id', single((req, res) => admin.updateCase(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/cases/:id/field-updates', single((req, res) => admin.addFieldUpdate(res.locals.actor as Actor, routeId(req), req.body), 201));
router.post('/admin/cases/:id/verify', single((req, res) => admin.verifyCase(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/cases/:id/analyze', expensive, single((req, res) => integrations.analyzeCase(res.locals.actor as Actor, routeId(req))));
router.post('/admin/cases/:id/assignments', single((req, res) => admin.assignTeam(res.locals.actor as Actor, routeId(req), req.body), 201));
router.patch('/admin/assignments/:id', single((req, res) => admin.updateAssignment(res.locals.actor as Actor, routeId(req), req.body)));
router.get('/admin/reports', list((req, res) => reports.listReports(res.locals.actor as Actor, req.query, true)));
router.get('/admin/reports/:id', single((req, res) => reports.getReport(res.locals.actor as Actor, routeId(req), true)));
router.post('/admin/reports/:id/case', writes, single((req, res) => admin.createReportCase(res.locals.actor as Actor, routeId(req), req.body), 201));
router.get('/admin/reports/:id/candidates', expensive, list((req, res) => admin.reportCandidates(res.locals.actor as Actor, routeId(req), req.query)));
router.patch('/admin/reports/:id', single((req, res) => admin.reviewReport(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/reports/:id/action', writes, single((req, res) => admin.submitReportAction(res.locals.actor as Actor, routeId(req), req.body), 201));
router.post('/admin/reports/:id/progress', writes, single((req, res) => reports.addReportProgress(res.locals.actor as Actor, routeId(req), req.body), 201));
router.post('/admin/reports/:id/updates', single((req, res) => reports.addReportUpdate(res.locals.actor as Actor, routeId(req), req.body), 201));
router.get('/admin/completion-reports', list(req => admin.listCompletionReports(req.query)));
router.get('/admin/completion-reports/:id', single(req => admin.getCompletionReport(routeId(req))));
router.post('/admin/completion-reports', writes, single((req, res) => admin.saveCompletionReport(res.locals.actor as Actor, req.body), 201));
router.post('/admin/completion-reports/:id/publish', writes, single((req, res) => admin.publishCompletionReport(res.locals.actor as Actor, routeId(req), req.body)));
router.get('/admin/monitoring/summary', single(() => admin.monitoringSummary()));
router.get('/admin/users', list(req => admin.listUsers(req.query)));
router.get('/admin/users/:id/avatar', async (req, res) => {
  const bytes = await readAdminAvatar(routeId(req));
  res.setHeader('Cache-Control', 'private, no-store');
  res.setHeader('Content-Type', 'image/jpeg');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.send(bytes);
});
router.post('/admin/users/:id/avatar', expensive, raw({ type: 'image/jpeg', limit: '1mb' }), single((req, res) => saveAdminAvatar(res.locals.actor as Actor, routeId(req), { expectedUpdatedAt: req.get('X-Blazemap-Expected-Updated-At'), reason: auditReason(req.get('X-Blazemap-Audit-Reason')) }, req.body)));
router.get('/admin/users/:id', single(req => admin.getUser(routeId(req))));
router.patch('/admin/users/:id', single((req, res) => admin.updateUser(res.locals.actor as Actor, routeId(req), req.body)));
router.get('/admin/operations', single(() => admin.operations()));
router.get('/admin/teams/:id', single(req => admin.getTeam(routeId(req))));
router.get('/admin/equipment/:id', single(req => admin.getEquipment(routeId(req))));
router.get('/admin/assignments/:id', single(req => admin.getAssignment(routeId(req))));
router.get('/admin/operational-features/:id', single(req => admin.getOperationalFeature(routeId(req))));
router.post('/admin/teams', writes, single((req, res) => admin.createTeam(res.locals.actor as Actor, req.body), 201));
router.patch('/admin/teams/:id', writes, single((req, res) => admin.updateTeam(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/equipment', writes, single((req, res) => admin.createEquipment(res.locals.actor as Actor, req.body), 201));
router.patch('/admin/equipment/:id', writes, single((req, res) => admin.updateEquipment(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/operational-features', writes, single((req, res) => admin.createOperationalFeature(res.locals.actor as Actor, req.body), 201));
router.post('/admin/operational-updates', writes, single((req, res) => admin.addOperationalUpdate(res.locals.actor as Actor, req.body), 201));
router.post('/admin/information/:id/media', single((req, res) => uploads.approveMedia(res.locals.actor as Actor, routeId(req), req.body), 201));
router.post('/admin/media/:id/revoke', single((req, res) => uploads.revokeMedia(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/outcomes/publish', writes, single((req, res) => admin.publishOutcome(res.locals.actor as Actor, req.body), 201));
router.get('/admin/information', list(req => admin.listInformation(req.query, true)));
router.post('/admin/information', single((req, res) => admin.saveInformation(res.locals.actor as Actor, req.body), 201));
router.get('/admin/information/:id', single(req => admin.getInformation(routeId(req), true)));
router.patch('/admin/information/:id', single((req, res) => admin.saveInformation(res.locals.actor as Actor, req.body, routeId(req))));
router.post('/admin/information/:id/publish', single((req, res) => admin.publishInformation(res.locals.actor as Actor, routeId(req), req.body)));
router.post('/admin/information/:id/withdraw', single((req, res) => admin.withdrawInformation(res.locals.actor as Actor, routeId(req), req.body)));
router.get('/admin/settings', single(() => admin.getSettings(true)));
router.patch('/admin/settings', single((req, res) => admin.updateSettings(res.locals.actor as Actor, req.body)));
router.post('/admin/integrations/:source/sync', expensive, single((req, res) => integrations.syncSource(routeId(req, 'source'), req.body, res.locals.actor as Actor)));
export default router;
